# Generated by Django 5.0.6 on 2024-07-08 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0002_question_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='icon',
        ),
    ]
